services:
  postgres:
    image: postgres:latest
    container_name: teebay_database
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


  backend:
    build: ./backend
    container_name: teebay_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - SECRET_KEY=03cud0)5uaclj74=f8p%w9ywocvm_%2qhda$155lxd3h)6znql
    depends_on:
      - postgres
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: teebay_frontend
    ports:
      - "3000:3000"
    volumes:
        - ./frontend:/opt/
    depends_on:
      - backend
    command: >
        bash -c "npm start"
